### ISSUE TITLE
Database hangs when look for character profiles

### ISSUE THREAD

**Issue by thaalesalves** [chatrpg-cs/chatrpg-be#2]
### Issue category
**Type:** Bug

### Issue description
Malaquias is able to retrieve a player's character's profile when either the player is directly mentioned or when their nickname shows on the message list sent to the AI. This problem occurs during this stage, and after converting the derived query method name into an actual SQL query, the select hangs and the bot stops responding.

**Comment by thaalesalves** [comment]
We can consider using a different DBMS. We spoke about converting to a NoSQL DB, or at least a non-relational one that's faster. We can DB possibilities and see one that works better and faster for our use case. Mongo, maybe?

**Comment by MagicShel** [comment]
I worked with Mongo once years ago. I think I could make that work. I've never used NoSQL, but that might be closer to a traditional database. Mongo is more like a service that just passes JSON back and forth.

**Comment by thaalesalves** [comment]
Mongo and Cassandra both sound like a good choice for me.

**Comment by thaalesalves** [comment]
Cassandra is SQL but non-relational, it's quite robust. When we speak our little server, sounds like overkill. But when we speak multiple servers with a buttload of text being processed... might make more sense.

**Comment by thaalesalves** [comment]
Let's experiment with Mongo. It could solve the problem we're having with PostgreSQL

**Comment by thaalesalves** [comment]
Fixed by changed mechanic for name extraction
