### ISSUE TITLE
Idea: use reactions to flag intent to the AI.

### ISSUE THREAD

**Issue by MagicShel** [chatrpg-cs/chatrpg-be#32]
The AI could interpret certain reactions as directives. For example 👎 might tell the AI to ignore a message (which you don't want to delete for some reason). A ⭐ might tell the AI to flag something as important in the memory.

Expand on this idea.
🛑 Ignore this message and all previous messages. Leave out of context.
👎 Ignore this message (maybe pick a different icon so it doesn't seem judgmental of the comment)
⭐ Make this message important somehow (move closer to front of context?)

**Comment by thaalesalves** [comment]
This could be tricky to implement, but it's a good idea. Gives more freedom to the story as we can't directly edit it as we would in AID, KAI or NAI. Buuuut, who should be able to do it? In larger servers, what if someone just wants to troll and keeps giving it thumbs down or the stop thing? How to circumvent that?

**Comment by thaalesalves** [comment]
Suggestions discussed with Monky:
📝: opens modal to edit message
❌: removes the message from context
🔄: deletes this message and retries the generation

**Comment by thaalesalves** [comment]
And instead of looking for these emojis, they would be added automatically after a message by the bot is sent.

**Comment by thaalesalves** [comment]
Using default emojis proved tricky. We added a mechanic to limit context on a specific message by using a custom emoji. We're gonna need custom emoji for the rest too.

**Comment by thaalesalves** [comment]
Ah, it supports the specific emoji for that but we forgot to make the bot itself add the emoji. The emojis should all be added by the bot itself.

**Comment by thaalesalves** [comment]
Migrated to JIRA
