### ISSUE TITLE
Use RegEx to dynamically insert data into prompt

### ISSUE THREAD

**Issue by MagicShel** [chatrpg-cs/chatrpg-be#9]
1. Add table to database with columns: id,loreId,pattern. loreId should be a FK to the current data table.
2. Hook the service to load all patterns and run them on the prompt. On matches, insert the corresponding lore at the top of the prompt.
3. A given loreId should be inserted no more than once, no matter how many patterns are associated with it.

Questions:
1. Should there be some sort of cap on the amount of lore to insert? What happens with that boundary is exceeded?
2. Should we add any sort of priority ranking to lore in case there is too much to insert it all?

**Comment by thaalesalves** [comment]
Adding this as in progress because Mongo supports this feature. Let's experiment with it.

**Comment by thaalesalves** [comment]
Fixed with [3aa8849f5b59424b672079be260b06602a84f484](https://github.com/thaalesalves/malaquias/commit/3aa8849f5b59424b672079be260b06602a84f484)
